"""Pydantic schemas for EvalRAG API requests and responses.

These models define the contract between frontend and backend, enforce validation,
and provide structured documentation for the API.
"""

from typing import Literal, get_args

from pydantic import BaseModel, Field, field_validator

Strategy = Literal["classic", "graph", "agentic"]
Provider = Literal["anthropic", "openai", "local"]


class _QuestionMixin(BaseModel):
    """Shared validation: a question must contain more than whitespace."""

    @field_validator("question", check_fields=False)
    @classmethod
    def _question_is_not_blank(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("question cannot be blank")
        return stripped


class Source(BaseModel):
    """A source chunk used to ground an answer.

    Attributes:
        chunk_id: Unique identifier for the retrieved chunk.
        quote: The exact text from the chunk that supports the answer.
        score: Retrieval score (0-1) indicating relevance confidence.
               None if score is not applicable for this strategy.

    Example:
        {
            "chunk_id": "doc_123_chunk_5",
            "quote": "Claude is an AI assistant made by Anthropic.",
            "document": "about_claude.md",
            "score": 0.92
        }
    """

    chunk_id: str = Field(description="Unique chunk identifier")
    quote: str = Field(description="Exact text from the chunk supporting the answer")
    document: str | None = Field(
        default=None,
        description="Filename this chunk came from. Used to score retrieval "
        "against a golden example's expected_sources, and to show a readable "
        "citation instead of a chunk hash.",
    )
    score: float | None = Field(
        default=None, ge=0, le=1, description="Relevance score (0-1)"
    )


class Answer(BaseModel):
    """A generated answer with sources and confidence.

    Attributes:
        question: The question that was asked.
        answer: The generated answer text.
        sources: List of chunks grounding the answer.
        confidence: Model's confidence in the answer (0-1).
        refusal: Whether the model refused to answer.
        provider: The LLM provider used (anthropic, openai, local).
        model: The specific model ID used for generation.

    Example:
        {
            "question": "Who built Claude?",
            "answer": "Claude was built by Anthropic, an AI safety company.",
            "sources": [
                {
                    "chunk_id": "doc_1_chunk_0",
                    "quote": "Claude is an AI assistant made by Anthropic.",
                    "score": 0.95
                }
            ],
            "confidence": 0.89,
            "refusal": false,
            "provider": "anthropic",
            "model": "claude-sonnet-5"
        }
    """

    question: str = Field(description="The question asked")
    answer: str = Field(description="The generated answer text")
    sources: list[Source] = Field(
        min_length=1, description="Chunks supporting this answer"
    )
    confidence: float = Field(
        ge=0, le=1, description="Model confidence in the answer (0-1)"
    )
    refusal: bool = Field(
        default=False, description="Whether the model refused to answer"
    )
    provider: str | None = Field(
        default=None, description="LLM provider (anthropic, openai, local)"
    )
    model: str | None = Field(
        default=None, description="Specific model ID used (e.g. claude-sonnet-5)"
    )
    latency_ms: int = Field(
        default=0, ge=0, description="End-to-end time to produce this answer (ms)"
    )
    input_tokens: int = Field(
        default=0, ge=0, description="Tokens sent to the model"
    )
    output_tokens: int = Field(
        default=0, ge=0, description="Tokens generated by the model"
    )


class Chunk(BaseModel):
    """A document chunk in the vector store.

    Attributes:
        id: Unique identifier for this chunk.
        doc_id: ID of the source document.
        text: The chunk text content.
        tokens: Approximate token count.
        section: Optional section/heading within the document.
        metadata: Additional metadata (source, page_number, etc.).

    Example:
        {
            "id": "doc_123_chunk_5",
            "doc_id": "doc_123",
            "text": "Claude is an AI assistant made by Anthropic...",
            "tokens": 150,
            "section": "About",
            "metadata": {
                "source": "blog.md",
                "page_number": 2
            }
        }
    """

    id: str = Field(description="Unique chunk identifier")
    doc_id: str = Field(description="Parent document ID")
    text: str = Field(description="Chunk content text")
    tokens: int = Field(ge=0, description="Approximate token count")
    section: str | None = Field(
        default=None, description="Section/heading within document"
    )
    metadata: dict = Field(
        default_factory=dict, description="Additional metadata (source, page, etc.)"
    )


class AskRequest(_QuestionMixin):
    """Request to ask a question and get an answer.

    Attributes:
        question: The question to answer.
        top_k: Number of chunks to retrieve (1-100, default 8).
        provider: Override default LLM provider (anthropic, openai, local).
        model: Override default model ID.
        prompt_version: Optional prompt variant identifier.
        strategy: RAG strategy to use (classic, graph, agentic).

    Example:
        {
            "question": "How does Claude handle security?",
            "top_k": 10,
            "strategy": "classic",
            "model": "claude-sonnet-5"
        }
    """

    question: str = Field(
        min_length=1, max_length=4000, description="Question to answer"
    )
    top_k: int | None = Field(
        default=None,
        ge=1,
        le=50,
        description="Chunks to keep after reranking. Defaults to RERANK_TOP_K.",
    )
    provider: Provider | None = Field(default=None, description="Override LLM provider")
    model: str | None = Field(
        default=None, max_length=128, description="Override model ID"
    )
    prompt_version: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[A-Za-z0-9._-]+$",
        description="Optional prompt variant",
    )
    strategy: Strategy = Field(
        default="classic", description="RAG strategy: classic, graph, or agentic"
    )


class CompareVariant(BaseModel):
    """One model/provider configuration in a comparison.

    Example:
        {"provider": "anthropic", "model": "claude-sonnet-5", "strategy": "classic"}
    """

    provider: Provider | None = Field(default=None, description="LLM provider")
    model: str | None = Field(default=None, max_length=128, description="Model ID")
    prompt_version: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[A-Za-z0-9._-]+$",
        description="Prompt template version",
    )
    strategy: Strategy = Field(default="classic", description="RAG strategy")


class CompareRequest(_QuestionMixin):
    """Request to compare multiple model/provider combinations.

    Attributes:
        question: The question to compare on.
        variants: List of configurations to compare
                 (provider, model, prompt_version, etc.).

    Example:
        {
            "question": "What is RAG?",
            "variants": [
                {"provider": "anthropic", "model": "claude-sonnet-5"},
                {"provider": "openai", "model": "gpt-4o-mini"}
            ]
        }
    """

    question: str = Field(
        min_length=1, max_length=4000, description="Question to compare on"
    )
    variants: list[CompareVariant] = Field(
        min_length=1,
        max_length=6,
        description="Model/provider configurations to compare",
    )


class CompareStrategiesRequest(_QuestionMixin):
    """Request to compare RAG strategies on the same question.

    Attributes:
        question: The question to run through all strategies.
        strategies: List of strategies to compare (classic, graph, agentic).
        model: Optional model override for all strategies.

    Example:
        {
            "question": "How are embeddings used in RAG?",
            "strategies": ["classic", "graph", "agentic"],
            "model": "claude-sonnet-5"
        }
    """

    question: str = Field(
        min_length=1, max_length=4000, description="Question to compare strategies on"
    )
    strategies: list[Strategy] = Field(
        default_factory=lambda: list(get_args(Strategy)),
        min_length=1,
        max_length=3,
        description="Strategies to compare: classic, graph, agentic",
    )
    model: str | None = Field(
        default=None, max_length=128, description="Optional model override"
    )


class EvalRunRequest(BaseModel):
    """Request to run evaluation on a dataset.

    Attributes:
        dataset: Golden dataset to evaluate against (e.g., golden_v1).
        provider: Override default LLM provider.
        model: Override default model ID.
        prompt_version: Optional prompt variant identifier.

    Example:
        {
            "dataset": "golden_v1",
            "strategy": "graph",
            "model": "claude-sonnet-5"
        }
    """

    dataset: str = Field(
        default="golden_v1",
        min_length=1,
        max_length=64,
        pattern=r"^[A-Za-z0-9._-]+$",
        description="Golden dataset name",
    )
    strategy: Strategy = Field(
        default="classic",
        description="RAG strategy to evaluate. Run once per strategy to compare them.",
    )
    provider: Provider | None = Field(
        default=None, description="Override LLM provider"
    )
    model: str | None = Field(
        default=None, max_length=128, description="Override model ID"
    )
    prompt_version: str | None = Field(
        default=None,
        max_length=64,
        pattern=r"^[A-Za-z0-9._-]+$",
        description="Optional prompt variant",
    )


class EvalScore(BaseModel):
    """Evaluation scores for an answer.

    Attributes:
        faithfulness: How much the answer sticks to retrieved context (0-1).
        answer_relevance: How relevant the answer is to the question (0-1).
        context_precision: Fraction of retrieved context that supports the answer (0-1).
        context_recall: Fraction of relevant context that was retrieved (0-1).

    Example:
        {
            "faithfulness": 0.95,
            "answer_relevance": 0.88,
            "context_precision": 0.92,
            "context_recall": 0.85
        }
    """

    faithfulness: float = Field(
        description="How faithful to retrieved context (0-1)"
    )
    answer_relevance: float = Field(
        description="Relevance of answer to question (0-1)"
    )
    context_precision: float = Field(
        description="Precision of retrieved context (0-1)"
    )
    context_recall: float = Field(description="Recall of relevant context (0-1)")


class RetrievalScore(BaseModel):
    """How well retrieval found the documents a golden example expects.

    Computed by comparing the documents behind an answer's sources against the
    example's `expected_sources`. Entirely deterministic -- no model call -- so
    these numbers are available even when the LLM judge is unavailable, and they
    are the metric that separates retrieval strategies most cleanly.

    Attributes:
        precision: Fraction of cited documents that were expected (0-1).
        recall: Fraction of expected documents that were cited (0-1).
        hit: Whether at least one expected document was cited.
        mrr: Reciprocal rank of the first expected document (1.0 if it ranked
            first, 0.5 if second, 0.0 if absent).
        retrieved: Documents behind the answer's sources, best-ranked first.
        expected: Documents the golden example expects.

    Example:
        {
            "precision": 0.5, "recall": 1.0, "hit": true, "mrr": 1.0,
            "retrieved": ["rag_overview.md", "chunking_strategies.md"],
            "expected": ["rag_overview.md"]
        }
    """

    precision: float = Field(ge=0, le=1, description="Cited docs that were expected")
    recall: float = Field(ge=0, le=1, description="Expected docs that were cited")
    hit: bool = Field(description="At least one expected document was cited")
    mrr: float = Field(ge=0, le=1, description="Reciprocal rank of the first hit")
    retrieved: list[str] = Field(
        default_factory=list, description="Documents cited, best first"
    )
    expected: list[str] = Field(
        default_factory=list, description="Documents the example expects"
    )


class HumanRatingRequest(BaseModel):
    """Request to rate an answer manually.

    Attributes:
        question: The question that was answered.
        answer: The answer text.
        rating: Human rating (1-5 stars).
        comment: Optional comment explaining the rating.
        provider: LLM provider used.
        model: Model ID used.
        prompt_version: Prompt variant used.

    Example:
        {
            "question": "What is machine learning?",
            "answer": "Machine learning is a subset of AI...",
            "rating": 5,
            "comment": "Accurate and comprehensive.",
            "model": "claude-sonnet-5"
        }
    """

    question: str = Field(min_length=1, max_length=4000, description="The question")
    answer: str = Field(min_length=1, max_length=20000, description="The answer text")
    rating: int = Field(ge=1, le=5, description="Rating (1-5 stars)")
    comment: str | None = Field(
        default=None, max_length=2000, description="Optional comment on the rating"
    )
    provider: str | None = Field(default=None, description="LLM provider")
    model: str | None = Field(default=None, description="Model ID")
    prompt_version: str | None = Field(default=None, description="Prompt variant")


class HumanRating(HumanRatingRequest):
    """A recorded human rating with metadata.

    Extends HumanRatingRequest with storage metadata.

    Attributes:
        id: Unique rating identifier.
        created_at: ISO 8601 timestamp when rating was created.

    Example:
        {
            "question": "What is machine learning?",
            "answer": "Machine learning is a subset of AI...",
            "rating": 5,
            "comment": "Accurate and comprehensive.",
            "model": "claude-sonnet-5",
            "id": "rating_12345",
            "created_at": "2024-08-07T14:30:00Z"
        }
    """

    id: str = Field(description="Unique rating ID")
    created_at: str = Field(description="ISO 8601 creation timestamp")


class StrategyComparison(BaseModel):
    """Result of running one strategy on a question.

    Used internally to compare strategies side-by-side.

    Attributes:
        strategy: Strategy name (classic, graph, agentic).
        question: The question answered.
        answer: The generated answer.
        sources: Retrieved sources supporting the answer.
        confidence: Model confidence (0-1).
        refusal: Whether the model refused.
        latency_ms: Response time in milliseconds.
        input_tokens: Tokens sent to the model.
        output_tokens: Tokens received from the model.
        iterations: For agentic strategy, tool calls made.
        trace: Structured trace events for debugging.
        extra: Additional metadata.

    Example:
        {
            "strategy": "classic",
            "question": "What is RAG?",
            "answer": "RAG combines retrieval and generation...",
            "sources": [...],
            "confidence": 0.92,
            "refusal": false,
            "latency_ms": 1240,
            "input_tokens": 450,
            "output_tokens": 125,
            "iterations": 1,
            "trace": [...],
            "extra": {}
        }
    """

    strategy: str = Field(description="Strategy name (classic, graph, agentic)")
    question: str = Field(description="The question")
    answer: str = Field(description="The answer")
    sources: list[Source] = Field(description="Retrieved sources")
    confidence: float = Field(ge=0, le=1, description="Confidence (0-1)")
    refusal: bool = Field(default=False, description="Whether model refused")
    latency_ms: int = Field(ge=0, description="Response time (ms)")
    input_tokens: int = Field(ge=0, description="Tokens sent to model")
    output_tokens: int = Field(ge=0, description="Tokens from model")
    iterations: int = Field(ge=0, description="Tool calls (agentic only)")
    trace: list[dict] = Field(
        default_factory=list, description="Structured trace events"
    )
    extra: dict = Field(default_factory=dict, description="Additional metadata")
